import { describe, expect, it } from 'vitest'
import { encodeV2Push, parseV2Capabilities, parseV2PushResponse } from './encryptedSyncV2'
const id='123e4567-e89b-42d3-a456-426614174001'
const request=()=>({protocol_version:2 as const,encrypted_sync_version:2 as const,device_id:id,items:[{event:{event_id:id,project_id:'p',entity_id:'n',entity_type:'note' as const,operation:'resolution' as const,revision:2,updated_at:'2026-01-01T00:00:00.000000Z',deleted_at:null},object:{crypto_version:1 as const,aad_version:1 as const,nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',ciphertext:'AAAAAAAAAAAAAAAAAAAAAA'}}]})
describe('encrypted sync v2',()=>{
 it('validates dormant capability and exact opaque resolution wire data',()=>{expect(parseV2Capabilities({supported_transport_version:2,writer_transport_version:2,cutover_epoch:0})).toMatchObject({writer_transport_version:2});expect(JSON.parse(encodeV2Push(request())).items[0].event.operation).toBe('resolution')})
 it('rejects malformed capability, envelope and receipt sets',()=>{expect(()=>parseV2Capabilities({supported_transport_version:2,writer_transport_version:3,cutover_epoch:0})).toThrow();const bad=request();bad.items[0]!.object.nonce='=';expect(()=>encodeV2Push(bad)).toThrow();expect(()=>parseV2PushResponse({protocol_version:2,encrypted_sync_version:2,results:[],current_cursor:0},[id])).toThrow()})
 it('requires one unique receipt per event',()=>{expect(parseV2PushResponse({protocol_version:2,encrypted_sync_version:2,results:[{event_id:id,server_sequence:1,duplicate:true}],current_cursor:1},[id]).results[0]!.duplicate).toBe(true)})
 it('rejects non-canonical identity, duplicate events and invalid backend metadata before HTTP',()=>{const uppercase=request();uppercase.device_id=id.toUpperCase();expect(()=>encodeV2Push(uppercase)).toThrow();const duplicate=request();duplicate.items.push(duplicate.items[0]!);expect(()=>encodeV2Push(duplicate)).toThrow();const invalidTimestamp=request();invalidTimestamp.items[0]!.event.updated_at='not-a-timestamp';expect(()=>encodeV2Push(invalidTimestamp)).toThrow();const oversizedProject=request();oversizedProject.items[0]!.event.project_id='p'.repeat(513);expect(()=>encodeV2Push(oversizedProject)).toThrow()})
 it('rejects foreign or non-canonical receipts and duplicate server sequences',()=>{const other='123e4567-e89b-42d3-a456-426614174002';expect(()=>parseV2PushResponse({protocol_version:2,encrypted_sync_version:2,results:[{event_id:other,server_sequence:1,duplicate:false}],current_cursor:1},[id])).toThrow();expect(()=>parseV2PushResponse({protocol_version:2,encrypted_sync_version:2,results:[{event_id:id.toUpperCase(),server_sequence:1,duplicate:false}],current_cursor:1},[id])).toThrow();expect(()=>parseV2PushResponse({protocol_version:2,encrypted_sync_version:2,results:[{event_id:id,server_sequence:1,duplicate:false},{event_id:other,server_sequence:1,duplicate:false}],current_cursor:1},[id,other])).toThrow()})
})
