// @vitest-environment node
import { describe, it, expect } from 'vitest';
import { asAccountMasterKey } from '@/crypto';
import { frameCatalogEvent, unframeCatalogEvent, sealCatalogEvent, openCatalogEvent, validateCatalogEvent, type CatalogEvent } from './accountCatalogCodec';
import { encodeAccountPush } from '@/api/encryptedSyncV3';
const USER = '123e4567-e89b-42d3-a456-426614174000', DEVICE = '123e4567-e89b-42d3-a456-426614174001', EVENT = '123e4567-e89b-42d3-a456-426614174002', PARENT = '123e4567-e89b-42d3-a456-426614174003', NOW = '2026-10-02T00:00:00.000000Z';
export function catalogEvent(): CatalogEvent { return { version: 1, header: { account_id: USER, scope: 'account', device_id: DEVICE, entity_type: 'folder', entity_id: '📁', event_id: EVENT, operation: 'create', parent_event_ids: [], revision: 1, generation: 1, updated_at: NOW }, payload: { name: 'Work' }, dependencies: { folders: {}, projects: {}, memberships: {} }, deleted_at: null }; }
describe('account catalog codec', () => {
    it('strict deterministic canonical frame and uncompressed bounds', () => { const e = catalogEvent(), frame = frameCatalogEvent(e); expect(unframeCatalogEvent(frame)).toEqual(e); expect(frameCatalogEvent(unframeCatalogEvent(frame))).toEqual(frame); const bad = frame.slice(); bad[11] = 1; expect(() => unframeCatalogEvent(bad)).toThrow(); expect(() => validateCatalogEvent({ ...e, extra: true })).toThrow(); expect(() => validateCatalogEvent({ ...e, payload: { name: 'x', path: '/secret' } })).toThrow(); expect(() => validateCatalogEvent({ ...e, payload: { name: '\ud800' } })).toThrow(); });
    it('all four units reject duplicates, unknown dependency keys and incomplete proofs', () => { const folder = catalogEvent(); const membership: CatalogEvent = { ...folder, header: { ...folder.header, entity_type: 'folder_membership', entity_id: 'C1' }, payload: { folder_id: 'F1' }, dependencies: { folders: { F1: [PARENT] }, projects: { C1: { bootstrap_id: PARENT, metadata_event_id: EVENT } }, memberships: {} } }; expect(unframeCatalogEvent(frameCatalogEvent(membership))).toEqual(membership); const order: CatalogEvent = { ...folder, header: { ...folder.header, entity_type: 'project_order', entity_id: 'project_order' }, payload: { ids: ['C1'] }, dependencies: { folders: {}, projects: membership.dependencies.projects, memberships: { C1: [PARENT] } } }; expect(() => validateCatalogEvent(order)).not.toThrow(); expect(() => validateCatalogEvent({ ...order, payload: { ids: ['C1', 'C1'] } })).toThrow(); expect(() => validateCatalogEvent({ ...order, dependencies: { ...order.dependencies, memberships: {} } })).toThrow(); const f: CatalogEvent = { ...folder, header: { ...folder.header, entity_type: 'folder_order', entity_id: 'folder_order' }, payload: { ids: ['F1'] }, dependencies: { folders: { F1: [PARENT] }, projects: {}, memberships: {} } }; expect(() => validateCatalogEvent(f)).not.toThrow(); expect(() => validateCatalogEvent({ ...f, header: { ...f.header, entity_id: 'anything' } })).toThrow(); });
    it('uses production v2 exclusively, fresh nonce and closed account wire', async () => { const e = catalogEvent(), amk = asAccountMasterKey(new Uint8Array(32)), o = await sealCatalogEvent(amk, e), other = await sealCatalogEvent(amk, e); expect(o.crypto_version).toBe(2); expect(o.nonce).not.toEqual(other.nonce); expect(await openCatalogEvent(amk, USER, e.header.entity_id, 'folder', o)).toEqual(e); await expect(openCatalogEvent(amk, DEVICE, e.header.entity_id, 'folder', o)).rejects.toThrow(); const wire = JSON.parse(encodeAccountPush(DEVICE, [{ event: { event_id: EVENT, canonical_user_id: USER, scope: 'account', entity_id: e.header.entity_id, entity_type: 'folder', operation: 'upsert', revision: 1, updated_at: NOW, deleted_at: null }, object: o }])); expect(wire.items[0].event).not.toHaveProperty('project_id'); expect(wire.items[0].object.crypto_version).toBe(2); });
    it('resolution parents are sorted unique, generation and revision bounded', () => { const e = catalogEvent(); e.header.operation = 'resolution'; e.header.revision = 2; e.header.generation = 2; e.header.parent_event_ids = [PARENT]; expect(() => validateCatalogEvent(e)).not.toThrow(); e.header.parent_event_ids = [PARENT, PARENT]; expect(() => validateCatalogEvent(e)).toThrow(); e.header.parent_event_ids = [EVENT]; expect(() => validateCatalogEvent(e)).toThrow(); });
});
