import contract from './documentCodecV1.contract.json'
import {canonical} from './projectMetadataCodec'
import {canonicalizeSyncTimestamp} from './syncTimestamp'
export interface DocumentHeader {account_id:string;device_id:string;project_id:string;stage_id:string|null;entity_id:string;event_id:string;bootstrap_id:string;metadata_event_id:string;stage_event_ids:string[];parents:string[];revision:number;generation:number;operation:'create'|'update'|'delete'|'resolution';updated_at:string}
export interface PortableDocument {id:string;project_id:string;stage_id:string|null;title:string;content_json:Record<string,unknown>;content_format:'tiptap-json/v1';created_at:string|null;extensions:Record<string,never>}
export interface DocumentEvent {version:1;header:DocumentHeader;mutation:'upsert'|'delete';document:PortableDocument|null;deleted_at:string|null}
export class DocumentCodecError extends Error {constructor(readonly code:string){super(code)}}
const fail=(code='invalid_document_payload'):never=>{throw new DocumentCodecError(code)}
const enc=new TextEncoder(),dec=new TextDecoder('utf-8',{fatal:true})
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))fail();return v as Record<string,unknown>}
const text=(v:unknown,max:number):v is string=>{if(typeof v!=='string'||enc.encode(v).length>max||v.includes('\0'))return false;for(let i=0;i<v.length;i++){const c=v.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const n=v.charCodeAt(++i);if(!(n>=0xdc00&&n<=0xdfff))return false}else if(c>=0xdc00&&c<=0xdfff)return false}return true}
const id=(v:unknown):v is string=>text(v,512)&&!!v
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(v)
const timestamp=(v:unknown)=>{try{return typeof v==='string'&&canonicalizeSyncTimestamp(v)===v}catch{return false}}
function exact(v:unknown,allowed:string[],required=allowed){const o=obj(v);if(required.some(k=>!Object.hasOwn(o,k))||Object.keys(o).some(k=>!allowed.includes(k)))fail('document_unsupported_structure');return o}
function attrs(v:unknown,allowed:string[]){for(const[k,value]of Object.entries(obj(v))){if(!allowed.includes(k)||value!==null&&typeof value!=='string'&&typeof value!=='number')fail('document_unsupported_structure');if(!['level','start'].includes(k)&&value!==null&&typeof value!=='string')fail();if(k==='textAlign'&&value!==null&&!['left','center','right','justify'].includes(String(value)))fail();if(typeof value==='string'&&!text(value,2048))fail('document_resource_limit');if(k==='level'&&(!Number.isInteger(value)||Number(value)<1||Number(value)>6))fail();if(k==='start'&&(!Number.isSafeInteger(value)||Number(value)<1))fail();if(k==='href'&&typeof value==='string'&&!/^(https?:\/\/|mailto:|#)/.test(value))fail('document_unsupported_structure')}}
function preflight(value:unknown){let bytes=0;const stack=[{value,depth:0}];while(stack.length){const{value:v,depth}=stack.pop()!;if(depth>160)fail('document_resource_limit');if(typeof v==='string'){if(!text(v,8388608))fail();bytes+=enc.encode(JSON.stringify(v)).length}else if(Array.isArray(v)){bytes+=2+v.length;for(const value of v)stack.push({value,depth:depth+1})}else if(v&&typeof v==='object'){const o=obj(v);bytes+=2+Object.keys(o).length+Object.keys(o).reduce((n,k)=>n+enc.encode(k).length+3,0);for(const value of Object.values(o))stack.push({value,depth:depth+1})}else{if(typeof v==='number'&&!Number.isFinite(v)||v!==null&&typeof v!=='number'&&typeof v!=='boolean')fail();bytes+=32}if(bytes>contract.limits.frame_bytes-20)fail('document_resource_limit')}}
export function validateTiptap(value:unknown){preflight(value);const stack=[{node:value,depth:0,parent:'',mark:false}];let count=0;while(stack.length){const{node,depth,parent,mark}=stack.pop()!;if(++count>50000||depth>60)fail('document_resource_limit');const n=exact(node,['type','attrs','content','text','marks'],['type']);const type=String(n.type),allowed=(mark?contract.marks:contract.nodes) as Record<string,string[]>;if(!Object.hasOwn(allowed,type))fail('document_unsupported_structure');if(depth===0&&type!=='doc'||depth>0&&!mark&&type==='doc')fail();if(Object.hasOwn(n,'attrs'))attrs(n.attrs,allowed[type]!);if(mark){if(['content','text','marks'].some(k=>Object.hasOwn(n,k)))fail();continue}const inline=['text','hardBreak'].includes(type);if(parent){const ok=parent==='codeBlock'?type==='text':['paragraph','heading'].includes(parent)?inline:['bulletList','orderedList'].includes(parent)?type==='listItem':['doc','listItem','blockquote'].includes(parent)?!inline&&type!=='listItem':false;if(!ok)fail()}if(type==='text'){if(!text(n.text,1048576)||!n.text)fail('document_resource_limit');if(Object.hasOwn(n,'content'))fail()}else if(Object.hasOwn(n,'text'))fail();if(Object.hasOwn(n,'marks')){if(type!=='text'||!Array.isArray(n.marks))fail();const seen=new Set();for(const m of n.marks as unknown[]){const type=obj(m).type;if(seen.has(type))fail();seen.add(type);stack.push({node:m,depth:depth+1,parent:'',mark:true})}}if(type==='heading'&&!Number.isInteger(obj(n.attrs).level))fail();if(['doc','blockquote','bulletList','orderedList','listItem'].includes(type)&&(!Array.isArray(n.content)||!n.content.length))fail();if(type==='listItem'&&obj((n.content as unknown[])[0]).type!=='paragraph')fail();if(parent==='codeBlock'&&Object.hasOwn(n,'marks')&&(!Array.isArray(n.marks)||n.marks.length))fail();if(Object.hasOwn(n,'content')){if(!Array.isArray(n.content)||['text','hardBreak','horizontalRule'].includes(type))fail();for(const child of n.content as unknown[])stack.push({node:child,depth:depth+1,parent:type,mark:false})}}}
export function validatePortableDocument(value:unknown):asserts value is PortableDocument {const d=exact(value,['id','project_id','stage_id','title','content_json','content_format','created_at','extensions']);if(!id(d.id)||!id(d.project_id)||d.stage_id!==null&&!id(d.stage_id)||!text(d.title,4096)||d.content_format!=='tiptap-json/v1'||d.created_at!==null&&!timestamp(d.created_at))fail();if(Object.keys(obj(d.extensions)).length)fail('document_unsupported_extension');validateTiptap(d.content_json)}
export function validateDocumentEvent(value:unknown):asserts value is DocumentEvent {preflight(value);const e=exact(value,['version','header','mutation','document','deleted_at']);const h=exact(e.header,['account_id','device_id','project_id','stage_id','entity_id','event_id','bootstrap_id','metadata_event_id','stage_event_ids','parents','revision','generation','operation','updated_at']);if(e.version!==1||['account_id','device_id','event_id','bootstrap_id','metadata_event_id'].some(k=>!uuid(h[k]))||!id(h.project_id)||!id(h.entity_id)||h.stage_id!==null&&!id(h.stage_id)||!timestamp(h.updated_at)||!Number.isSafeInteger(h.revision)||Number(h.revision)<1||h.generation!==h.revision)fail();for(const key of ['parents','stage_event_ids']){const a=h[key];if(!Array.isArray(a)||a.length>64||a.some((x,i)=>!uuid(x)||x===h.event_id||i>0&&a[i-1]>=x))fail()}const parents=h.parents as string[];if((h.stage_id===null)!==((h.stage_event_ids as string[]).length===0))fail();if(h.operation==='create'?parents.length!==0||h.revision!==1:['update','delete'].includes(String(h.operation))?parents.length!==1||Number(h.revision)<2:h.operation==='resolution'?parents.length<2||Number(h.revision)<2:true)fail();if(e.mutation==='upsert'){validatePortableDocument(e.document);const d=e.document;if(e.deleted_at!==null||h.operation==='delete'||d.id!==h.entity_id||d.project_id!==h.project_id||d.stage_id!==h.stage_id)fail()}else if(e.mutation!=='delete'||e.document!==null||e.deleted_at!==h.updated_at||!['delete','resolution'].includes(String(h.operation)))fail()}
export async function frameDocumentEvent(e:DocumentEvent):Promise<Uint8Array>{validateDocumentEvent(e);const body=enc.encode(canonical(e));if(body.length+20>contract.limits.frame_bytes)fail('document_resource_limit');const out=new Uint8Array(body.length+20);out.set(enc.encode('WORTA-C1'));out.set([1,10,1,0],8);const view=new DataView(out.buffer);view.setUint32(12,body.length);view.setUint32(16,body.length);out.set(body,20);return out}
export async function unframeDocumentEvent(frame:Uint8Array):Promise<DocumentEvent>{if(frame.length>contract.limits.frame_bytes)fail('document_resource_limit');if(frame.length<20||dec.decode(frame.subarray(0,8))!=='WORTA-C1'||frame[8]!==1||frame[9]!==10||frame[10]!==1||frame[11]!==0)fail('document_codec_unsupported');const view=new DataView(frame.buffer,frame.byteOffset,frame.byteLength);if(view.getUint32(12)!==frame.length-20||view.getUint32(16)!==frame.length-20)fail();let raw:string,value:unknown;try{raw=dec.decode(frame.subarray(20));value=JSON.parse(raw)}catch{fail()}validateDocumentEvent(value);if(canonical(value)!==raw!)fail();return value}
