import { compressionBlocker } from './frameCompression'
import {invoke} from '@tauri-apps/api/core'
import {encryptedSyncV3Api} from '@/api/encryptedSyncV3'
import {syncApi} from '@/api/sync'
import {decryptObjectBytes,encryptObjectBytes} from '@/crypto'
import {KeyNotProvisionedError} from '@/auth/keyContext'
import {StaleAuthContextError} from '@/auth/userAuth'
import {diagnostics} from '@/diagnostics/service'
import {ProjectMetadataMigrationRuntime} from './projectMetadataMigrationRuntime'
import {NOTE_READER_SUPPORT} from './contentNoteRuntime'
import {unframeDocumentEvent,type DocumentEvent} from './documentCodec'
import {canonicalizeSyncTimestamp} from './syncTimestamp'
import type {MetadataScope} from '@/infrastructure/sqlite/projectMetadataMigrationRepository'
export interface DocumentOwnerView {entity_id:string;stage_id:string|null;state:string;blocker:string|null;tips:string[];versions:Array<{event_id:string;revision:number;stage_id?:string|null;mutation:string;document:DocumentEvent['document']}>;local:unknown}
export interface DocumentApplyResult {blocked:string[];hasRemainingWork:boolean;listed:number;applied:number;conflicts:number}
export interface DocumentAuthorityView {owners:DocumentOwnerView[];blocker?:string|null}
export interface DocumentDecision {project_id:string;expected_tips:string[];expected_local:unknown;document_id:string;selected_event_id:string}
interface Pending{event:DocumentEvent;frame:number[];nonce:number[]|null;ciphertext:number[]|null}
interface Incoming{event_id:string;server_sequence:number;source_device_id:string;project_id:string;entity_id:string;revision:number;updated_at:string;nonce:number[];ciphertext:number[]}
export class DocumentSyncError extends Error{constructor(readonly code:string){super(code)}}
const now=()=>canonicalizeSyncTimestamp(new Date().toISOString())
export const DOCUMENT_READER_SUPPORT={frame_version:1,codec_id:10,codec_version:1,reader_version:1,compression_zero:true} as const
const native=<T>(scope:MetadataScope,request:unknown):Promise<T>=>invoke<T>('document_sync_command',{scope,request})
/** Capability advertising never captures data. Only beginDocuments is publication consent. */
export class DocumentSyncRuntime extends ProjectMetadataMigrationRuntime{
 async declareSupport(account:string,device:string){const {scope,context}=await this.scope(account,device);await this.auth.authorized(t=>syncApi.registerDevice(t,device));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.noteReaderCapabilities(t,device,NOTE_READER_SUPPORT));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.documentReaderCapabilities(t,device,DOCUMENT_READER_SUPPORT));this.assertCurrent(context);return scope}
 private async gate(account:string,device:string){await this.requireMode3(account,device);const {scope,context}=await this.scope(account,device);const gate=await this.auth.authorized(t=>encryptedSyncV3Api.documentReaderGate(t));this.assertCurrent(context);if(!gate.value.ready)throw new DocumentSyncError('document_readers_not_ready');return {scope,context}}
 async viewDocuments(account:string,device:string,project:string):Promise<DocumentAuthorityView>{const {scope,context}=await this.scope(account,device);const view=await native<DocumentAuthorityView>(scope,{action:'view',project_id:project});this.assertCurrent(context);return view}
 async beginDocuments(account:string,device:string,project:string):Promise<DocumentAuthorityView>{await this.declareSupport(account,device);const {scope,context}=await this.gate(account,device);const view=await native<DocumentAuthorityView>(scope,{action:'begin',project_id:project,now:now()});this.assertCurrent(context);diagnostics.record('migrations','document_migration','succeeded',undefined,{count:view.owners.length});return view}
 async chooseDocument(account:string,device:string,decision:DocumentDecision,keepLocal?:boolean):Promise<void>{const {scope,context}=await this.gate(account,device);await native(scope,{action:'decide',decision:{...decision,selected_event_id:keepLocal?'local':decision.selected_event_id},now:now()});this.assertCurrent(context);diagnostics.record('sync','document_resolution','succeeded',undefined,{count:1})}
 async moveDocument(account:string,device:string,project:string,id:string,stage:string|null,expected:unknown):Promise<void>{const {scope,context}=await this.gate(account,device);await native(scope,{action:'move',project_id:project,document_id:id,stage_id:stage,expected,now:now()});this.assertCurrent(context)}
 async deleteDocument(account:string,device:string,project:string,id:string,expected:unknown):Promise<void>{const {scope,context}=await this.gate(account,device);await native(scope,{action:'delete',project_id:project,document_id:id,expected,now:now()});this.assertCurrent(context)}
 async sealDocuments(account:string,device:string):Promise<number>{const {scope,context}=await this.gate(account,device);const items=await native<Pending[]>(scope,{action:'pending',sealed:false,now:now()});this.assertCurrent(context);for(const item of items){const original=Uint8Array.from(item.frame);let bytes:Uint8Array=original;try{const e=await unframeDocumentEvent(bytes);if(e.header.account_id!==context.userId||e.header.device_id!==device)throw new DocumentSyncError('document_scope_mismatch');const lease=this.keys.leaseForAccount(account);if(!lease)throw new KeyNotProvisionedError();await lease.use(async amk=>{const h=e.header;bytes=await this.compressionFrame(account,device,original);const sealed=await encryptObjectBytes(amk,{userId:h.account_id,projectId:h.project_id,entityType:'document',entityId:h.entity_id},bytes);this.assertCurrent(context);await native(scope,{action:'seal',event_id:h.event_id,frame:Array.from(bytes),nonce:Array.from(sealed.nonce),ciphertext:Array.from(sealed.ciphertext)});this.assertCurrent(context)})}finally{bytes.fill(0);original.fill(0)}}return items.length}
 async uploadDocuments(account:string,device:string):Promise<number>{const {scope,context}=await this.gate(account,device);const items=await native<Pending[]>(scope,{action:'pending',sealed:true,now:now()});this.assertCurrent(context);for(const item of items){const h=item.event.header;if(!item.nonce||!item.ciphertext||h.account_id!==context.userId||h.device_id!==device)throw new DocumentSyncError('document_scope_mismatch');const response=await this.auth.authorized(t=>encryptedSyncV3Api.pushDocuments(t,device,[{event:{event_id:h.event_id,project_id:h.project_id,entity_id:h.entity_id,entity_type:'document',operation:'event',revision:h.revision,updated_at:h.updated_at,deleted_at:null},object:{crypto_version:1,aad_version:1,nonce:Uint8Array.from(item.nonce!),ciphertext:Uint8Array.from(item.ciphertext!)}}]));this.assertCurrent(context);const receipt=response.value.results[0];if(response.value.results.length!==1||receipt?.event_id!==h.event_id)throw new DocumentSyncError('document_receipt_mismatch');await native(scope,{action:'receipt',event_id:h.event_id,server_sequence:receipt.server_sequence,duplicate:receipt.duplicate,now:now()});this.assertCurrent(context)}diagnostics.record('sync','document_writer','upload_result',undefined,{count:items.length});return items.length}
 async readOnce(account:string,device:string,limit=8,passes=4):Promise<DocumentApplyResult>{await this.requireMode3(account,device);if(!Number.isInteger(limit)||limit<1||limit>32||!Number.isInteger(passes)||passes<1||passes>8)throw new RangeError('invalid_document_page');const {scope,context}=await this.scope(account,device);let listed=0,applied=0,conflicts=0;const blocked:string[]=[];let remaining=false;let after=0;
  for(let pass=0;pass<passes;pass++){const items=await native<Incoming[]>(scope,{action:'received',after,limit});this.assertCurrent(context);if(!items.length)break;listed+=items.length;remaining=items.length===limit;let progressed=false;
   for(const row of items){let bytes:Uint8Array|undefined;try{const lease=this.keys.leaseForAccount(account);if(!lease)throw new KeyNotProvisionedError();const status=await lease.use(async amk=>{bytes=await decryptObjectBytes(amk,{userId:context.userId,projectId:row.project_id,entityType:'document',entityId:row.entity_id},{crypto_version:1,aad_version:1,nonce:Uint8Array.from(row.nonce),ciphertext:Uint8Array.from(row.ciphertext)});this.assertCurrent(context);const e=await unframeDocumentEvent(bytes),h=e.header;if(h.account_id!==context.userId||h.device_id!==row.source_device_id||h.event_id!==row.event_id||h.entity_id!==row.entity_id||h.project_id!==row.project_id||h.revision!==row.revision||h.updated_at!==row.updated_at)throw new DocumentSyncError('document_scope_mismatch');const status=await native<string>(scope,{action:'apply',frame:Array.from(bytes),nonce:row.nonce,ciphertext:row.ciphertext});this.assertCurrent(context);return status});if(status==='applied'||status==='conflict_preserved'){progressed=true;if(status==='applied')applied++;else conflicts++}else{blocked.push(status);remaining=true}diagnostics.record('sync','document_apply','apply_result',undefined,{status,count:1})}catch(error){if(error instanceof StaleAuthContextError)throw error;this.assertCurrent(context);const known=['document_codec_unsupported','document_resource_limit','document_unsupported_extension','document_unsupported_structure','document_scope_mismatch'];const candidate=error instanceof Error?error.message:'';const code=compressionBlocker(error) ?? (known.includes(candidate)?candidate:bytes?'invalid_document_payload':'decrypt_failed');blocked.push(code);remaining=true;await native(scope,{action:'block',event_id:row.event_id,nonce:row.nonce,ciphertext:row.ciphertext,code});this.assertCurrent(context)}finally{bytes?.fill(0)}}
   after=items[items.length-1]!.server_sequence;
   if(items.length<limit){if(!progressed)break;after=0}
  }return {blocked,hasRemainingWork:remaining||blocked.length>0,listed,applied,conflicts}
 }
}
