// @vitest-environment node
import {it,expect} from 'vitest'
import fixture from './__fixtures__/documentCodecV1.json'
import {frameDocumentEvent,unframeDocumentEvent,validateTiptap,type DocumentEvent} from './documentCodec'
import {asAccountMasterKey,encryptObjectBytes,decryptObjectBytes} from '@/crypto'
it('codec10 cross-language vectors, frames and stable identity',async()=>{for(const v of fixture.examples){const e=v.event as DocumentEvent;const frame=await frameDocumentEvent(e);expect(Buffer.from(frame).toString('hex')).toBe(v.frame_hex);expect(await unframeDocumentEvent(frame)).toEqual(e);for(const i of [9,10,11,12]){const bad=frame.slice();bad[i]=bad[i]!^1;await expect(unframeDocumentEvent(bad)).rejects.toThrow()}}const e=structuredClone(fixture.examples[0]!.event) as DocumentEvent;e.header.entity_id='foreign';await expect(frameDocumentEvent(e)).rejects.toThrow()})
it('rejects unsupported extensions, editor structures and resource excess without rewriting',async()=>{const e=structuredClone(fixture.examples[0]!.event) as DocumentEvent;Object.assign(e.document!.extensions,{legacy_flag:true});await expect(frameDocumentEvent(e)).rejects.toThrow('document_unsupported_extension');expect(e.document!.extensions).toEqual({legacy_flag:true});expect(()=>validateTiptap({type:'doc',content:[{type:'image',attrs:{src:'/private/path'}}]})).toThrow();expect(()=>validateTiptap({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'a'.repeat(1048577)}]}]})).toThrow('document_resource_limit');let tree:unknown={type:'paragraph'};for(let i=0;i<65;i++)tree={type:'blockquote',content:[tree]};expect(()=>validateTiptap({type:'doc',content:[tree]})).toThrow('document_resource_limit')})
it('retains C11 project/document cryptographic isolation',async()=>{const e=fixture.examples[0]!.event as DocumentEvent;const key=asAccountMasterKey(new Uint8Array(32).fill(17));const scope={userId:e.header.account_id,projectId:e.header.project_id,entityType:'document',entityId:e.header.entity_id};const frame=await frameDocumentEvent(e),o=await encryptObjectBytes(key,scope,frame);expect(await decryptObjectBytes(key,scope,o)).toEqual(frame);for(const wrong of [{...scope,userId:'123e4567-e89b-42d3-a456-426614174099'},{...scope,projectId:'foreign'},{...scope,entityId:'foreign'},{...scope,entityType:'map'}])await expect(decryptObjectBytes(key,wrong,o)).rejects.toThrow()})

it('validates editor structural grammar and hard node bound',()=>{for(const content of [{type:'doc',content:[{type:'paragraph',attrs:{textAlign:12}}]},{type:'doc',content:[{type:'paragraph',attrs:{textAlign:'unknown'}}]},{type:'doc'},{type:'doc',content:[{type:'heading',content:[]}]},{type:'doc',content:[{type:'listItem',content:[{type:'paragraph'}]}]},{type:'doc',content:[{type:'bulletList',content:[{type:'listItem',content:[{type:'blockquote',content:[{type:'paragraph'}]}]}]}]},{type:'doc',content:[{type:'codeBlock',content:[{type:'hardBreak'}]}]}])expect(()=>validateTiptap(content)).toThrow();expect(()=>validateTiptap({type:'doc',content:Array.from({length:50000},()=>({type:'paragraph'}))})).toThrow('document_resource_limit')})
