import {invoke} from '@tauri-apps/api/core'
import {encryptedSyncV3Api} from '@/api/encryptedSyncV3'
import {syncApi} from '@/api/sync'
import {decryptObjectBytes,encryptObjectBytes} from '@/crypto'
import {KeyNotProvisionedError} from '@/auth/keyContext'
import {StaleAuthContextError} from '@/auth/userAuth'
import {diagnostics} from '@/diagnostics/service'
import {ProjectMetadataMigrationRuntime} from './projectMetadataMigrationRuntime'
import {NOTE_READER_SUPPORT} from './contentNoteRuntime'
import {unframeMapEvent,type MapEvent} from './mapCodec'
import {canonicalizeSyncTimestamp} from './syncTimestamp'
import type {MetadataScope} from '@/infrastructure/sqlite/projectMetadataMigrationRepository'
export interface MapOwnerView {entity_id:string;stage_id:string|null;state:string;blocker:string|null;tips:string[];versions:Array<{event_id:string;revision:number;mutation:string;map:MapEvent['map']}>;local:unknown}
export interface MapApplyResult {blocked:string[];hasRemainingWork:boolean;listed:number;applied:number;conflicts:number}
export interface MapAuthorityView {owners:MapOwnerView[]}
export interface MapDecision {project_id:string;stage_id:string|null;expected_tips:string[];expected_local:unknown;selected_event_id:string}
interface Pending{event:MapEvent;frame:number[];nonce:number[]|null;ciphertext:number[]|null}
interface Incoming{event_id:string;server_sequence:number;source_device_id:string;project_id:string;entity_id:string;revision:number;updated_at:string;nonce:number[];ciphertext:number[]}
export class MapSyncError extends Error{constructor(readonly code:string){super(code)}}
const now=()=>canonicalizeSyncTimestamp(new Date().toISOString())
export const MAP_READER_SUPPORT={frame_version:1,codec_id:9,codec_version:1,reader_version:1,compression_zero:true} as const
const native=<T>(scope:MetadataScope,request:unknown):Promise<T>=>invoke<T>('map_sync_command',{scope,request})
/** Capability advertising never captures data. Only beginMaps is publication consent. */
export class MapSyncRuntime extends ProjectMetadataMigrationRuntime{
 async declareSupport(account:string,device:string){const {scope,context}=await this.scope(account,device);await this.auth.authorized(t=>syncApi.registerDevice(t,device));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.noteReaderCapabilities(t,device,NOTE_READER_SUPPORT));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.mapReaderCapabilities(t,device,MAP_READER_SUPPORT));this.assertCurrent(context);return scope}
 private async gate(account:string,device:string){await this.requireMode3(account,device);const {scope,context}=await this.scope(account,device);const gate=await this.auth.authorized(t=>encryptedSyncV3Api.mapReaderGate(t));this.assertCurrent(context);if(!gate.value.ready)throw new MapSyncError('map_readers_not_ready');return {scope,context}}
 async viewMaps(account:string,device:string,project:string):Promise<MapAuthorityView>{const {scope,context}=await this.scope(account,device);const view=await native<MapAuthorityView>(scope,{action:'view',project_id:project});this.assertCurrent(context);return view}
 async beginMaps(account:string,device:string,project:string):Promise<MapAuthorityView>{await this.declareSupport(account,device);const {scope,context}=await this.gate(account,device);const view=await native<MapAuthorityView>(scope,{action:'begin',project_id:project,now:now()});this.assertCurrent(context);diagnostics.record('migrations','map_migration','succeeded',undefined,{count:view.owners.length});return view}
 async chooseMap(account:string,device:string,decision:MapDecision,keepLocal?:boolean):Promise<void>{const {scope,context}=await this.gate(account,device);await native(scope,keepLocal===undefined?{action:'decide',decision,now:now()}:{action:'import',decision,keep_local:keepLocal,now:now()});this.assertCurrent(context);diagnostics.record('sync','map_resolution','succeeded',undefined,{count:1})}
 async sealMaps(account:string,device:string):Promise<number>{const {scope,context}=await this.gate(account,device);const items=await native<Pending[]>(scope,{action:'pending',sealed:false,now:now()});this.assertCurrent(context);for(const item of items){const bytes=Uint8Array.from(item.frame);try{const e=await unframeMapEvent(bytes);if(e.header.account_id!==context.userId||e.header.device_id!==device)throw new MapSyncError('map_scope_mismatch');const lease=this.keys.leaseForAccount(account);if(!lease)throw new KeyNotProvisionedError();await lease.use(async amk=>{const h=e.header;const sealed=await encryptObjectBytes(amk,{userId:h.account_id,projectId:h.project_id,entityType:'map',entityId:h.entity_id},bytes);this.assertCurrent(context);await native(scope,{action:'seal',event_id:h.event_id,frame:item.frame,nonce:Array.from(sealed.nonce),ciphertext:Array.from(sealed.ciphertext)});this.assertCurrent(context)})}finally{bytes.fill(0)}}return items.length}
 async uploadMaps(account:string,device:string):Promise<number>{const {scope,context}=await this.gate(account,device);const items=await native<Pending[]>(scope,{action:'pending',sealed:true,now:now()});this.assertCurrent(context);for(const item of items){const h=item.event.header;if(!item.nonce||!item.ciphertext||h.account_id!==context.userId||h.device_id!==device)throw new MapSyncError('map_scope_mismatch');const response=await this.auth.authorized(t=>encryptedSyncV3Api.pushMaps(t,device,[{event:{event_id:h.event_id,project_id:h.project_id,entity_id:h.entity_id,entity_type:'map',operation:'event',revision:h.revision,updated_at:h.updated_at,deleted_at:null},object:{crypto_version:1,aad_version:1,nonce:Uint8Array.from(item.nonce!),ciphertext:Uint8Array.from(item.ciphertext!)}}]));this.assertCurrent(context);const receipt=response.value.results[0];if(response.value.results.length!==1||receipt?.event_id!==h.event_id)throw new MapSyncError('map_receipt_mismatch');await native(scope,{action:'receipt',event_id:h.event_id,server_sequence:receipt.server_sequence,duplicate:receipt.duplicate,now:now()});this.assertCurrent(context)}diagnostics.record('sync','map_writer','upload_result',undefined,{count:items.length});return items.length}
 async readOnce(account:string,device:string,limit=8,passes=4):Promise<MapApplyResult>{await this.requireMode3(account,device);if(!Number.isInteger(limit)||limit<1||limit>32||!Number.isInteger(passes)||passes<1||passes>8)throw new RangeError('invalid_map_page');const {scope,context}=await this.scope(account,device);let listed=0,applied=0,conflicts=0;const blocked:string[]=[];let remaining=false;let after=0;
  for(let pass=0;pass<passes;pass++){const items=await native<Incoming[]>(scope,{action:'received',after,limit});this.assertCurrent(context);if(!items.length)break;listed+=items.length;remaining=items.length===limit;let progressed=false;
   for(const row of items){let bytes:Uint8Array|undefined;try{const lease=this.keys.leaseForAccount(account);if(!lease)throw new KeyNotProvisionedError();const status=await lease.use(async amk=>{bytes=await decryptObjectBytes(amk,{userId:context.userId,projectId:row.project_id,entityType:'map',entityId:row.entity_id},{crypto_version:1,aad_version:1,nonce:Uint8Array.from(row.nonce),ciphertext:Uint8Array.from(row.ciphertext)});this.assertCurrent(context);const e=await unframeMapEvent(bytes),h=e.header;if(h.account_id!==context.userId||h.device_id!==row.source_device_id||h.event_id!==row.event_id||h.entity_id!==row.entity_id||h.project_id!==row.project_id||h.revision!==row.revision||h.updated_at!==row.updated_at)throw new MapSyncError('map_scope_mismatch');const status=await native<string>(scope,{action:'apply',frame:Array.from(bytes),nonce:row.nonce,ciphertext:row.ciphertext});this.assertCurrent(context);return status});if(status==='applied'||status==='conflict_preserved'){progressed=true;if(status==='applied')applied++;else conflicts++}else{blocked.push(status);remaining=true}diagnostics.record('sync','map_apply','apply_result',undefined,{status,count:1})}catch(error){if(error instanceof StaleAuthContextError)throw error;this.assertCurrent(context);const code=bytes?'invalid_map_payload':'decrypt_failed';blocked.push(code);remaining=true;await native(scope,{action:'block',event_id:row.event_id,nonce:row.nonce,ciphertext:row.ciphertext,code});this.assertCurrent(context)}finally{bytes?.fill(0)}}
   after=items[items.length-1]!.server_sequence;
   if(items.length<limit){if(!progressed)break;after=0}
  }return {blocked,hasRemainingWork:remaining||blocked.length>0,listed,applied,conflicts}
 }
}
