import { compressionBlocker } from './frameCompression'
import {invoke} from '@tauri-apps/api/core'
import {encryptedSyncV3Api} from '@/api/encryptedSyncV3'
import {syncApi} from '@/api/sync'
import {decryptObjectBytes,encryptObjectBytes} from '@/crypto'
import {KeyNotProvisionedError} from '@/auth/keyContext'
import {StaleAuthContextError} from '@/auth/userAuth'
import {diagnostics} from '@/diagnostics/service'
import {ProjectMetadataMigrationRuntime} from './projectMetadataMigrationRuntime'
import {NOTE_READER_SUPPORT} from './contentNoteRuntime'
import {unframeProgressEvent,type ProgressEvent} from './progressCodec'
import type {ProgressFact} from './progressCodec'
import {canonicalizeSyncTimestamp} from './syncTimestamp'
import type {MetadataScope} from '@/infrastructure/sqlite/projectMetadataMigrationRepository'
export interface ProgressChain {base_total:string;entries:ProgressFact[]}
export interface ProgressOwnerView {entity_id:string;stage_id:string|null;state:string;blocker:string|null;tips:string[];versions:Array<{event_id:string;chain:ProgressChain}>;local:unknown}
export interface ProgressApplyResult {blocked:string[];hasRemainingWork:boolean;listed:number;applied:number;conflicts:number}
export interface ProgressAuthorityView {owners:ProgressOwnerView[]}
export interface ProgressDecision {project_id:string;stage_id:string|null;expected_tips:string[];expected_local:unknown;selected_event_id:string;operation:'select'|'rebase'|'correct'|'tombstone'|'adopt_local';target_entry_id:string|null;rebased_from:string[];corrected_delta:string|null}
interface Pending{event:ProgressEvent;frame:number[];nonce:number[]|null;ciphertext:number[]|null}
interface Incoming{event_id:string;server_sequence:number;source_device_id:string;project_id:string;entity_id:string;revision:number;updated_at:string;nonce:number[];ciphertext:number[]}
export class ProgressSyncError extends Error{constructor(readonly code:string){super(code)}}
const now=()=>canonicalizeSyncTimestamp(new Date().toISOString())
export const PROGRESS_READER_SUPPORT={frame_version:1,codec_id:11,codec_version:1,reader_version:1,compression_zero:true} as const
const native=<T>(scope:MetadataScope,request:unknown):Promise<T>=>invoke<T>('progress_sync_command',{scope,request})
/** Capability advertising never captures data. Only beginProgress is publication consent. */
export class ProgressSyncRuntime extends ProjectMetadataMigrationRuntime{
 async declareSupport(account:string,device:string){const {scope,context}=await this.scope(account,device);await this.auth.authorized(t=>syncApi.registerDevice(t,device));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.noteReaderCapabilities(t,device,NOTE_READER_SUPPORT));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.mapReaderCapabilities(t,device,{frame_version:1,codec_id:9,codec_version:1,reader_version:1,compression_zero:true}));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.documentReaderCapabilities(t,device,{frame_version:1,codec_id:10,codec_version:1,reader_version:1,compression_zero:true}));this.assertCurrent(context);await this.auth.authorized(t=>encryptedSyncV3Api.progressReaderCapabilities(t,device,PROGRESS_READER_SUPPORT));this.assertCurrent(context);return scope}
 private async gate(account:string,device:string){await this.requireMode3(account,device);const {scope,context}=await this.scope(account,device);const gate=await this.auth.authorized(t=>encryptedSyncV3Api.progressReaderGate(t));this.assertCurrent(context);if(!gate.value.ready)throw new ProgressSyncError('progress_readers_not_ready');return {scope,context}}
 async viewProgress(account:string,device:string,project:string):Promise<ProgressAuthorityView>{const {scope,context}=await this.scope(account,device);const view=await native<ProgressAuthorityView>(scope,{action:'view',project_id:project});this.assertCurrent(context);return view}
 async beginProgress(account:string,device:string,project:string):Promise<ProgressAuthorityView>{await this.declareSupport(account,device);const {scope,context}=await this.gate(account,device);const view=await native<ProgressAuthorityView>(scope,{action:'begin',project_id:project,now:now()});this.assertCurrent(context);diagnostics.record('migrations','progress_migration','succeeded',undefined,{count:view.owners.length});return view}
 async chooseProgress(account:string,device:string,decision:ProgressDecision):Promise<void>{const {scope,context}=await this.gate(account,device);await native(scope,{action:'decide',decision,now:now()});this.assertCurrent(context);diagnostics.record('sync','progress_resolution','succeeded',undefined,{count:1})}
 async sealProgress(account:string,device:string):Promise<number>{const {scope,context}=await this.gate(account,device);const items=await native<Pending[]>(scope,{action:'pending',sealed:false,now:now()});this.assertCurrent(context);for(const item of items){const original=Uint8Array.from(item.frame);let bytes:Uint8Array=original;try{const e=await unframeProgressEvent(bytes);if(e.header.account_id!==context.userId||e.header.device_id!==device)throw new ProgressSyncError('progress_scope_mismatch');const lease=this.keys.leaseForAccount(account);if(!lease)throw new KeyNotProvisionedError();await lease.use(async amk=>{const h=e.header;bytes=await this.compressionFrame(account,device,original);const sealed=await encryptObjectBytes(amk,{userId:h.account_id,projectId:h.project_id,entityType:'progress',entityId:h.entity_id},bytes);this.assertCurrent(context);await native(scope,{action:'seal',event_id:h.event_id,frame:Array.from(bytes),nonce:Array.from(sealed.nonce),ciphertext:Array.from(sealed.ciphertext)});this.assertCurrent(context)})}finally{bytes.fill(0);original.fill(0)}}return items.length}
 async uploadProgress(account:string,device:string):Promise<number>{const {scope,context}=await this.gate(account,device);const items=await native<Pending[]>(scope,{action:'pending',sealed:true,now:now()});this.assertCurrent(context);for(const item of items){const h=item.event.header;if(!item.nonce||!item.ciphertext||h.account_id!==context.userId||h.device_id!==device)throw new ProgressSyncError('progress_scope_mismatch');const response=await this.auth.authorized(t=>encryptedSyncV3Api.pushProgress(t,device,[{event:{event_id:h.event_id,project_id:h.project_id,entity_id:h.entity_id,entity_type:'progress',operation:'event',revision:h.revision,updated_at:h.updated_at,deleted_at:null},object:{crypto_version:1,aad_version:1,nonce:Uint8Array.from(item.nonce!),ciphertext:Uint8Array.from(item.ciphertext!)}}]));this.assertCurrent(context);const receipt=response.value.results[0];if(response.value.results.length!==1||receipt?.event_id!==h.event_id)throw new ProgressSyncError('progress_receipt_mismatch');await native(scope,{action:'receipt',event_id:h.event_id,server_sequence:receipt.server_sequence,duplicate:receipt.duplicate,now:now()});this.assertCurrent(context)}diagnostics.record('sync','progress_writer','upload_result',undefined,{count:items.length});return items.length}
 async readOnce(account:string,device:string,limit=8,passes=4):Promise<ProgressApplyResult>{await this.requireMode3(account,device);if(!Number.isInteger(limit)||limit<1||limit>32||!Number.isInteger(passes)||passes<1||passes>8)throw new RangeError('invalid_progress_page');const {scope,context}=await this.scope(account,device);let listed=0,applied=0,conflicts=0;const blocked:string[]=[];let remaining=false;let after=0;
  for(let pass=0;pass<passes;pass++){const items=await native<Incoming[]>(scope,{action:'received',after,limit});this.assertCurrent(context);if(!items.length)break;listed+=items.length;remaining=items.length===limit;let progressed=false;
   for(const row of items){let bytes:Uint8Array|undefined;let applying=false;try{const lease=this.keys.leaseForAccount(account);if(!lease)throw new KeyNotProvisionedError();const status=await lease.use(async amk=>{bytes=await decryptObjectBytes(amk,{userId:context.userId,projectId:row.project_id,entityType:'progress',entityId:row.entity_id},{crypto_version:1,aad_version:1,nonce:Uint8Array.from(row.nonce),ciphertext:Uint8Array.from(row.ciphertext)});this.assertCurrent(context);const e=await unframeProgressEvent(bytes),h=e.header;if(h.account_id!==context.userId||h.device_id!==row.source_device_id||h.event_id!==row.event_id||h.entity_id!==row.entity_id||h.project_id!==row.project_id||h.revision!==row.revision||h.updated_at!==row.updated_at)throw new ProgressSyncError('progress_scope_mismatch');applying=true;const status=await native<string>(scope,{action:'apply',frame:Array.from(bytes),nonce:row.nonce,ciphertext:row.ciphertext});this.assertCurrent(context);return status});if(status==='applied'||status==='conflict_preserved'){progressed=true;if(status==='applied')applied++;else conflicts++}else{blocked.push(status);remaining=true}diagnostics.record('sync','progress_apply','apply_result',undefined,{status,count:1})}catch(error){if(error instanceof StaleAuthContextError||error instanceof KeyNotProvisionedError||applying)throw error;this.assertCurrent(context);const known=['progress_codec_unsupported','progress_resource_limit','progress_scope_mismatch'];const candidate=error instanceof Error?error.message:'';const code=compressionBlocker(error) ?? (known.includes(candidate)?candidate:bytes?'invalid_progress_payload':'decrypt_failed');blocked.push(code);remaining=true;await native(scope,{action:'block',event_id:row.event_id,nonce:row.nonce,ciphertext:row.ciphertext,code});this.assertCurrent(context)}finally{bytes?.fill(0)}}
   after=items[items.length-1]!.server_sequence;
   if(items.length<limit){if(!progressed)break;after=0}
  }return {blocked,hasRemainingWork:remaining||blocked.length>0,listed,applied,conflicts}
 }
}
