import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../frontend/src/cloud/__fixtures__/',import.meta.url));
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
export const corpus=[];
for(const file of ['projectMetadataV2.json','stageCodecV1.json','accountCatalogV1.json','contentNoteCodecV1.json','mapCodecV1.json','documentCodecV1.json','progressCodecV1.json','gameCodecV1.json']){
 const j=JSON.parse(fs.readFileSync(root+file));for(const [i,e]of (Array.isArray(j)?j:j.examples??[j.event?j:{event:j}]).entries()){if(e.event)corpus.push({name:file+':'+(e.name??i),canonical:canonical(e.event)})}
}
const metadata=JSON.parse(fs.readFileSync(root+'projectMetadataV2.json'))[0].event;const largeMeta=structuredClone(metadata);for(const key of ['name','unit','status','work_method'])largeMeta.metadata[key]='Writer α '.repeat(45);corpus.push({name:'metadata-larger',canonical:canonical(largeMeta)});
const stage=JSON.parse(fs.readFileSync(root+'stageCodecV1.json')).event;const order=structuredClone(stage);order.header.entity_type='stage_order';order.header.entity_id='stage_order';order.stage=null;order.stage_ids=Array.from({length:4096},(_,i)=>'stage-'+i);order.stage_heads=Object.fromEntries(order.stage_ids.map(id=>[id,[stage.header.event_id]]));corpus.push({name:'stage-order-large',canonical:canonical(order)});
const folder=JSON.parse(fs.readFileSync(root+'accountCatalogV1.json'));const folderOrder=structuredClone(folder);folderOrder.header.entity_type='folder_order';folderOrder.header.entity_id='folder_order';folderOrder.payload={ids:Array.from({length:2000},(_,i)=>'folder-'+i)};folderOrder.dependencies.folders=Object.fromEntries(folderOrder.payload.ids.map(id=>[id,[stage.header.event_id]]));corpus.push({name:'catalog-order-large',canonical:canonical(folderOrder)});
const doc=JSON.parse(fs.readFileSync(root+'documentCodecV1.json')).examples[0].event;
let seed=18701;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed};
const words=['Писатель','вчера','закончил','рукопись','ветер','читатель','the','writer','walked','across','quiet','room','α','🌿'];
for(const target of [1024,16384,262144,8200000]){const e=structuredClone(doc);const blocks=[];let size=0;while(size<target){let text='';for(let i=0;i<500;i++)text+=words[random()%words.length]+' ';blocks.push({type:'paragraph',content:[{type:'text',text}]});size+=Buffer.byteLength(text)}e.document.content_json={type:'doc',content:blocks};corpus.push({name:'document-prose-'+target,canonical:canonical(e)})}
// Natural sentence cases complement deliberately repetitive and random bands.
for(const target of [65536,1048576]){const e=structuredClone(doc),blocks=[];let total=0,i=0;const names=['Арина','Марк','Илья','София','Elena','Daniel','Anna','Noah'],places=['старого сада','городской библиотеки','тихой пристани','соседнего дома'],objects=['письмо','книгу','план следующей главы','вчерашнюю запись'];while(total<target){const name=names[random()%names.length],place=places[random()%places.length],object=objects[random()%objects.length];const text=`Запись ${++i}. Вечером ${name} остановился у ${place}. Нужно было проверить ${object}, но разговор снова вернулся к тому, что случилось накануне. Никто не торопился: за окном шёл дождь, и пустая улица казалась длиннее обычного. On day ${i}, the writer returned to the unfinished page. A small detail changed the direction of the story; the ending would have to wait until morning.`;blocks.push({type:'paragraph',content:[{type:'text',text}]});total+=Buffer.byteLength(text)}e.document.content_json={type:'doc',content:blocks};corpus.push({name:'document-narrative-'+target,canonical:canonical(e)})}
const note=JSON.parse(fs.readFileSync(root+'contentNoteCodecV1.json')).examples[0].event;
for(const format of ['plain','html']){const e=structuredClone(note);e.event.note.content_format=format;e.event.note.content=('Новая глава. The writer remembered the quiet sea. α 🌿 '+Array.from({length:500},()=>words[random()%words.length]).join(' ')).repeat(8);if(format==='html')e.event.note.content='<p>'+e.event.note.content+'</p>';corpus.push({name:'note-'+format,canonical:canonical(e)})}
const map=JSON.parse(fs.readFileSync(root+'mapCodecV1.json')).examples.find(x=>x.event.mutation==='upsert').event;const e=structuredClone(map);e.map.data={nodeData:{id:'root',topic:'Рукопись',children:Array.from({length:2000},(_,i)=>({id:'node-'+i,topic:words[random()%words.length]+' сюжет '+i,children:[]}))}};e.map.annotations={};corpus.push({name:'large-map',canonical:canonical(e)});
corpus.push({name:'tiny-policy-probe-not-entity',canonical:'{"message":"α"}'});
let randomText='';for(let i=0;i<65536;i++)randomText+=String.fromCharCode(33+random()%90);corpus.push({name:'random-policy-probe-not-entity',canonical:canonical({text:randomText})});
process.stdout.write(JSON.stringify(corpus));
