<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { adminApi, adminSession, type AdminUser, type RegistrationSettings, type ReservedUsername } from '@/api/admin'

const router = useRouter(); const users = ref<AdminUser[]>([]); const total = ref(0); const search = ref(''); const status = ref(''); const role = ref(''); const registration = ref<RegistrationSettings | null>(null); const globalLimit = ref(20); const reserved = ref<ReservedUsername[]>([]); const reservedName = ref(''); const error = ref('')
async function loadUsers(){ const q=new URLSearchParams({limit:'50'});if(search.value)q.set('search',search.value);if(status.value)q.set('status',status.value);if(role.value)q.set('role',role.value);const result=await adminApi.users(q.toString());users.value=result.users;total.value=result.total }
async function load(){try{await Promise.all([loadUsers(),adminApi.registration().then(v=>registration.value=v),adminApi.limits().then(v=>globalLimit.value=v.max_cloud_projects),adminApi.reserved().then(v=>reserved.value=v)])}catch(e){error.value=e instanceof Error?e.message:'Ошибка загрузки'}}
async function action(user:AdminUser, action:'approve'|'reject'|'block'|'unblock'|'revoke'){if(!confirm(`Подтвердить действие: ${action}?`))return; if(action==='revoke')await adminApi.revoke(user.id);else await adminApi.lifecycle(user.id,action);await loadUsers()}
async function saveRegistration(){if(registration.value)registration.value=await adminApi.saveRegistration({mode:registration.value.mode,max_users:registration.value.max_users})}
async function saveLimit(){await adminApi.saveLimits(globalLimit.value)}
async function setOverride(user:AdminUser){const raw=prompt('Лимит проектов (пусто — наследовать):',user.max_cloud_projects_override?.toString()??'');if(raw===null)return;await adminApi.userLimit(user.id,raw.trim()===''?null:Number(raw));await loadUsers()}
async function addReserved(){if(!reservedName.value.trim())return;await adminApi.addReserved(reservedName.value);reservedName.value='';reserved.value=await adminApi.reserved()}
async function removeReserved(name:string){if(confirm(`Удалить резервирование ${name}?`)){await adminApi.removeReserved(name);reserved.value=await adminApi.reserved()}}
async function logout(){try{await adminSession.logout()}finally{router.replace('/admin/login')}}
onMounted(load)
</script>
<template><main class="admin"><header><h1>Администрирование</h1><button class="nf-button" @click="logout">Выйти</button></header><p v-if="error" role="alert">{{error}}</p><section><h2>Пользователи ({{total}})</h2><form @submit.prevent="loadUsers"><input v-model="search" aria-label="Поиск" placeholder="Поиск"/><select v-model="status" aria-label="Статус"><option value="">Все статусы</option><option>pending</option><option>active</option><option>rejected</option><option>blocked</option></select><select v-model="role" aria-label="Роль"><option value="">Все роли</option><option>user</option><option>admin</option></select><button>Найти</button></form><table><thead><tr><th>Пользователь</th><th>Статус</th><th>Лимит</th><th>Действия</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td>{{user.username}}<br/><small>{{user.email}} · {{user.role}} · {{user.email_verified?'email подтверждён':'email не подтверждён'}}</small></td><td>{{user.status}}</td><td>{{user.effective_max_cloud_projects}} <small>{{user.max_cloud_projects_override===null?'(общий)':'(override)'}}</small></td><td v-if="user.role==='admin'">Защищён</td><td v-else><button v-if="user.status==='pending'||user.status==='rejected'" @click="action(user,'approve')">Одобрить</button><button v-if="user.status==='pending'" @click="action(user,'reject')">Отклонить</button><button v-if="user.status==='active'" @click="action(user,'block')">Блокировать</button><button v-if="user.status==='blocked'" @click="action(user,'unblock')">Разблокировать</button><button @click="action(user,'revoke')">Сессии</button><button @click="setOverride(user)">Лимит</button></td></tr></tbody></table></section><section v-if="registration"><h2>Регистрация</h2><select v-model="registration.mode"><option value="open">Открытая</option><option value="approval">По одобрению</option><option value="closed">Закрытая</option></select><label>Максимум пользователей <input v-model.number="registration.max_users" type="number" min="0" /></label><small>Активных: {{registration.active_users}}. Уменьшение не отключает существующие аккаунты.</small><button @click="saveRegistration">Сохранить</button></section><section><h2>Лимиты</h2><label>Максимум cloud-проектов <input v-model.number="globalLimit" type="number" min="0"/></label><button @click="saveLimit">Сохранить</button></section><section><h2>Зарезервированные имена</h2><form @submit.prevent="addReserved"><input v-model="reservedName" aria-label="Имя"/><button>Добавить</button></form><ul><li v-for="item in reserved" :key="item.username_normalized">{{item.username_normalized}} <button @click="removeReserved(item.username_normalized)">Удалить</button></li></ul></section></main></template>
<style scoped>.admin{max-width:75rem;margin:auto;padding:1.5rem;display:grid;gap:2rem}.admin header{display:flex;justify-content:space-between;align-items:center}section{display:grid;gap:.75rem}table{width:100%;border-collapse:collapse}td,th{padding:.5rem;border-bottom:1px solid var(--nf-color-border);text-align:left;vertical-align:top}button{margin:.15rem}input,select{padding:.45rem}</style>
