name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-
      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -workspace nfprogress.xcworkspace CODE_SIGNING_ALLOWED=NO -parallel-testing-enabled YES
      - name: Lint Text scaling
        run: bash Scripts/checkTextScale.sh
      - name: Boot simulator
        run: xcrun simctl boot "iPhone 15 Pro (latest)" || true
      - name: Run tests
        run: xcodebuild test -workspace nfprogress.xcworkspace -scheme nfprogress -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' CODE_SIGNING_ALLOWED=NO -parallel-testing-enabled YES
      - name: Shutdown simulator
        if: always()
        run: xcrun simctl shutdown all
